# Database settings
database:

  # *** Overridden in production by environment variables ***
  #   in prod we use postgres, h2 is nice for development
  driverClass: org.h2.Driver
  user: user
  password: password
  url: jdbc:h2:dev


# logging
logging:
  level: INFO

# server settings
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

# Max number of requests to service per user per second
rateLimit: 500
