# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sam

  # h2 requires no password, for development use only

  # the JDBC URL
  url: jdbc:h2:dev

# server settings
server:
  applicationConnectors:
    - type: http
      port: 8800

  adminConnectors:
    - type: http
      port: 8801

# Max number of requests to service per second
rateLimit: 100
